# These substitutions allow the end user to override certain values
substitutions:
  name: "cmd_rad_room_ss_sud"
  friendly_name: "Command thyristor radiateur chambre sous-sol sud"
  area: "Chambre"

  espidf_version: "5.3.0"
  platformio_version: "6.8.1"

packages:
  common: !include my_packages/common.yml
  device_base: !include my_boards/m5stack-nanoc6.yml 

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project: 
    name: "philippe_besson.cmd_thyristor_pour_radiateur_électrique"
    version: "0.0.1"

esp32:
  board: $board
  variant: $variant
  flash_size: $flash_size
  framework:
    type: esp-idf
    version: $espidf_version
    platform_version: $platformio_version    

# Enable Home Assistant API
api:
  encryption:
    key: "hHiW6RJKXzVRBqWr0Q62zmmIu0NsPZnrjaEsZq7lkuQ="

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.134.137
    gateway: 192.168.134.129
    subnet: 255.255.255.192   

  use_address: 192.168.134.137    

    
